language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile
- yarn install
install: yarn
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn run build
deploy:
  repo: Team-IF/teamif.github.io
  provider: pages:git
  fqdn: teamif.xyz
  target_branch: master
  local_dir: build
  github_token:
    secure: "bF6yI1JWYeiTIVr0KCbee3aUbcQVH37+bdBczKUuhX6r9UTQ/kjf+0r2xJU5Mu3uIkfawmxIvXxCzEbBIHKI+BtkKRM/7dNLfskU8bzx0DpKhuySarjXXcMBP1zexK54BghotwmJO6pXhnX4JMIa3SIDBRw8ft5izsECkaOeTRAOjW6/cTR0AFHZK/o7dGwVaHVYIKG7UKDXepWFhqZkg2Wf4Gq3WJ74
    EG5Ue7jgqslVIE8Jj8Vnlqvz+dC/bBIKXO47YKKjMIAtIh9mLVkskDufc5xU71T9++jQQnQ9AgNNwChF5dz9P0twug2iF6/4NsWrEB5sZw4ikaGsbjTk3jHsMj0mIRjYVv2X1FUzceFyujVUHMB5XiZq6lbEmxGoRI3w9Vw0xlIAOMb3+Kz1GGB+soapUYLJ+dSXwlrkzuwhaoSM7aNFPlDSRecra8T3ncmOR4cb7b2
    C5igVLVWBbWN6Qt14I4d+xSPVV4yLHi10VWJS+TtXf+8phv0j5jZrJAFGUnEcy9GzGbxWwvQdukw7MU+z8Av2sPqKTl0IZfTRrMgjegxR4ZrL02p3Z+N+3Kij7SpSrJu3DsTU7Sa+y3V3JIET+3cvV79sAlaXMlq4GDaCKqVPeUuh0Pd5uBXhn8doGJK/JJwIwK8FbCmjik34cqyFbT1gGflEk66DuFA="
  edge: true