language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add greenkeeper-lockfile
  - yarn install
install: yarn
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn run build
env:
  global:
    - secure: r9pmXdi4M8B8UBMGF1uHC6rwIWL2DOIVa5/xtxgrcaeVo+uXdR4L8YRT8Xt536tcrNrVSVbRjPCXP98BNEHSuKkfcdZMp5/5cjkwV+6ZdJABoMYf0I5u9iEDNM32XBHkMA3HRbha4xohLuojf+iHFmCbdZLwk1c+3I4UqCb4V4O1402rLl6RIi3Nmk7WTtfMD5N4D6qOLFvZswNnFtx5P0CgWkxrHLDhbdRI1GbAZ2p7NFrVbAXwcnwCXEmnZURIDoe1ejsH8ciHZXnhqUd5zcFBhJO1OTpVCLu0L6vhW4d9K132X2CjxfqbRlGO9Xo/a7lO29Ip7ZEyk5LQXp4/1QLhynfms227RpI+r7AijQ2Z2ocC3oj8pLowWU8Swt6VpyQUyxFkaUgLyg7nrNpQos/FwYhi9LPDUHnsUIAWnwAAYlarNKDGvOqA2/G17FkzjCM5m47wT929Vj8RMYWLkErSXysbOzWqO/uGr+7FMwdkWE/GvRtibBowgmbA+tXl7anWVLfOL1EF5BUQrNz4kVvt1WZW4keDpRbhB4GfiaP9mAITDLRSYQM5ICBO7EU1vdu8KHk46GlL9IWoOrKi0E7Nq7IPQulCvRXgju647jGLfCNszQMJr/f9w3cFdpwqKsxj14SNn309yeyihUw9wFiTfnDsdUUj6t6teyMfpdw=
    - secure: SeoXmMFrNUAS8Zb77DlUTyAg2Eglbb5+KgUWLrj7DUAxX/ASpdNRNLdDoMGutOJazFL7wuDQgFkIGxg9SrAa1NbdGzraKuO1hCKYySG3Ueo4MSe1kjmrBu2/vjZBfJANGPNI06kCwpVl7rHGHDp8yu2rb+Q4eBPUjR9VWRmWdFTNyvlZUvEqpAnWhF7fsbBbSWVKxaPdAzd4wMwBlTIas6sRrPdoWgBlWitvMJjXTRkFdrAki8rVYgEAZekPjvru3wFrCsZDEm9RecLh5qK6PfHkS0ZK9cVF2U8Q9X1griP6f8mgmLeS5qVkZMd4mthBWOu+W+Uc1deS1VWst4aqhnx+I2SdOJAfiMDNytDjrhXD9MT/AkAIpSH/+GNdn/Tb1HDQjQ6iMUpylbmhgkqAGqHFZA4IHmZclxSAZLBpOjNxBX/tnrQQYBIVaudKarBEVWgWMU28huUbFu3V9wcbMWUqHO2SmxjMeRJlxf+Vc48bsR0kfAziI5jRJd5HCJLdSHV6XolABSKTwyJ2Uc66i0YQvQ6vHHBVvpAlBvn2brCfhezu1nuD5jxhGWFv/S+bk0fp5V8uGlLz5taK5iMFE/3GOtuSk8O54xkGt7Wri1qFBQsEtO9b5648SaDjnG4OALx2Cki2cljo2pKW07FgbeB/KA34FbBmjJrOG55o5V0=
    - secure: ggZ/ytXxcTNM8OiTcZqlUltxwH+grpzqBcV0P1F+dRThbB4oHSSQYG2ZzF1ozbvkpwszcWz3XNUmAJdWexEcK+uO991Qw7wQUP1ME2WNGRdfdi9ey/2eMRB2wEPPkeHa2KMJxkds29NRDX9bmQ+0PHivncRYuOuJbWo7tIasq9wcKDzhaMc185RTountyl6jCT7AbCGSCsQ670DhP39Rcd3Y0jlpwl6GVD2k1OnMQFQY+0NtXKrX/lzsc3bN4s12oowx2CviAmB4cq2GFxa0SnyZvs90gqZNL0GfTxZVSrhnLFvHr7EpEbNOvtTvFnaScstfDO8xkRtz1KTt83WimH5z2OOLA29bzH6ke/fBZFwPgkVHczsnXBtvvOe1Xl2etF5hTsqrfw3LGEJatq3ZizCA3Cb5a8xmsaCLVOHziM+5ciaw7Gs/sxzcGDXrN5Lw3OJy6jMjPnSjfe0X8Hy2IAPi9mejmKi4eIf1mS3GAN3Mw/gM1zn6zqvMVbDiSAtEd1/jMyk9WkfiqINsCv/MdPH9sMiLTriLGeM4rOr1gXRSVZMul4rt/kAUS0aMrB3kJRZPGwoYsstV6Ss0qlMg0Y5DjAuCds83utsBBBnVM2CoxUc56rozhh7+6a8whhA3q0tkefZpsRq1cToaO5Ggui4QIFcryhmRYaQ7P/mCGZw=
after_success:
  - curl --ftp-create-dirs
    -T build/*
    sftp://${SFTP_USER}:${SFTP_PASSWORD}@${SFTP_ADDRESS}/root/teamif/