language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile
- yarn install
install: yarn
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn run build
env:
  global:
    - secure: r9pmXdi4M8B8UBMGF1uHC6rwIWL2DOIVa5/xtxgrcaeVo+uXdR4L8YRT8Xt536tcrNrVSVbRjPCXP98BNEHSuKkfcdZMp5/5cjkwV+6ZdJABoMYf0I5u9iEDNM32XBHkMA3HRbha4xohLuojf+iHFmCbdZLwk1c+3I4UqCb4V4O1402rLl6RIi3Nmk7WTtfMD5N4D6qOLFvZswNnFtx5P0CgWkxrHLDhbdRI1GbAZ2p7NFrVbAXwcnwCXEmnZURIDoe1ejsH8ciHZXnhqUd5zcFBhJO1OTpVCLu0L6vhW4d9K132X2CjxfqbRlGO9Xo/a7lO29Ip7ZEyk5LQXp4/1QLhynfms227RpI+r7AijQ2Z2ocC3oj8pLowWU8Swt6VpyQUyxFkaUgLyg7nrNpQos/FwYhi9LPDUHnsUIAWnwAAYlarNKDGvOqA2/G17FkzjCM5m47wT929Vj8RMYWLkErSXysbOzWqO/uGr+7FMwdkWE/GvRtibBowgmbA+tXl7anWVLfOL1EF5BUQrNz4kVvt1WZW4keDpRbhB4GfiaP9mAITDLRSYQM5ICBO7EU1vdu8KHk46GlL9IWoOrKi0E7Nq7IPQulCvRXgju647jGLfCNszQMJr/f9w3cFdpwqKsxj14SNn309yeyihUw9wFiTfnDsdUUj6t6teyMfpdw=
    - secure: kYiLX00uJjo4mDP3CRLsj0XhEOHaMzIPNnVL557hGSENnj8T8NrWYSrUs7UiICwwIEn9aR415KmoYR75VlAIhX77Rmz4OxRS8QzwrLV4wt6SCymwqj75i2RqFrr+tSRt4auu9bLm5XuJuflbqnA5ADe6a+U57GZI35YBPgZxtwmUGV0MHcoVIJXVUeIG9RmxM7s2x1IyooVExwAY7fbCGpH0LKLVja33RQKgm5ygmteU81HXkXylivCJ7iXnEnUGb7sr5fUebEIHVVx4lOfKtJE7V5EwuXq9Lo8l6fMb6jSbS/90nOHE53ynSViVINXTv4fpJXDXU3tWoAXD1cBHtEKqedYbwh87Ftw1FJFWtItdSE7pyukYiRDMhljgrT3O6QTnPpssSxtF/mWbFtnM5r8MNkJUyfnd1nkdktXa5YMzF8gYwMbYP9bNswhG3ZSx0i8IOWrsvDYG9StyC7y+HX7vaP8oJtFaR73FJdHNKhgB65Gv1KCXlpZrnTIkumuBMVQfN9yqmMWqZZ63oXrMF3UrZKxHdnsXWroKGKRRIsVf2bw8OZ+uQZGdysoBvGIy2tGHyd/eK5SPuQHsxjxQs5H5V+o0MbdU71W2BdJRc6v4nTU2xmzZYph9dYAAafDeObNuJFVSTw5LmXrHocYcW06alp+gRcNIj+BH7WaR+aQ=
after_success:
  - rsync -avz build/ -e 'ssh -p 1742 ${SFTP_USER}:${SFTP_PASSWORD}@teamif.io:/${SFTP_USER}/teamif/'
